version: '3.8'

x-network-driver:
  &network-driver
  driver: bridge

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: gunicorn src.main.wsgi:application --bind 0.0.0.0:8000 --workers 3
    volumes:
      - ./src/:/home/springnews/web/src/
      - static_volume:/home/springnews/web/staticfiles
    restart: on-failure
    expose:
      - 8000
    env_file:
      - ./.env
    depends_on:
      db:
        condition: service_healthy
    networks:
      - frontend-net
      - backend-net
    healthcheck:
      test: [ "CMD-SHELL", "curl 0.0.0.0:8000" ]
      interval: 10s
      timeout: 5s
      retries: 5

  db:
    image: postgres:14-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_DATABASE}
    networks:
      - backend-net
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d ${DB_DATABASE} -U ${DB_USERNAME}" ]
      interval: 10s
      timeout: 5s
      retries: 5

  nginx:
    build: ./nginx
    volumes:
      - static_volume:/home/springnews/web/staticfiles
    ports:
      - 1337:80
    depends_on:
       web:
        condition: service_healthy
    networks:
      - frontend-net

volumes:
  postgres_data:
  static_volume:

networks:
  backend-net:
    *network-driver
  frontend-net:
    *network-driver
